### ISSUE TITLE
Lesson QA feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-js-eslint#1]
@chrisvfritz
## Why consistency in code matters

My takeaway from this page is that inconsistent code is distracting and that's the main reason why it's bad.

Why is it called a linter?

**Comment by KatieMFritz** [comment]
## Setting up ESLint

The installation took a little while, but the steps were very clear.

**Comment by KatieMFritz** [comment]
## Configuring ESLint for your project

After creating the .js file, I got the following error:

```
Error: Failed to load plugin html: Cannot find module 'eslint-plugin-html'
Error: Failed to load plugin html: Cannot find module 'eslint-plugin-html'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.module.exports.load (C:\Users\Katie\.atom\packages\linter-eslint\node_modules\eslint\lib\config\plugins.js:114:26)
    at Array.forEach (native)
    at Object.module.exports.loadAll (C:\Users\Katie\.atom\packages\linter-eslint\node_modules\eslint\lib\config\plugins.js:136:21)
    at Object.load (C:\Users\Katie\.atom\packages\linter-eslint\node_modules\eslint\lib\config\config-file.js:500:21)
    at loadConfig (C:\Users\Katie\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:64:33)
    at new Config (C:\Users\Katie\.atom\packages\linter-eslint\node_modules\eslint\lib\config.js:197:38)
```

Update: it's because I hadn't checked `Lint HTML files`

**Comment by KatieMFritz** [comment]
## Project

I really liked this project. Short and sweet, but I learned several things:
- how to customize packages and settings in Atom (I've done it before, but this was a good reminder)
- some syntax errors in javascript that I'm likely to make
- why a linter rocks
